services:
  nareswara-comp:
    container_name: nareswara-comp
    image: nareswara-comp:latest
    build: .
    ports:
      - "8001:80"
    env_file: .env
    environment:
      - DB_HOST=db
      - DB_PORT=3306
    depends_on:
      - db
  
  db:
    image: mysql:8.0
    container_name: nareswara-db
    environment:
      MYSQL_DATABASE: nareswara_comp
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: